name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install SQLite3
      run: sudo apt-get update && sudo apt-get install -y sqlite3 libsqlite3-dev
    
    - name: Create directories
      run: mkdir -p build bin
    
    - name: Compile
      run: make
    
    - name: Test run
      run: ./bin/tourism_app --help || true
